1️⃣ Perceptron Simples (Churn)

Texto explicativo (Colab – bloco Markdown)

Modelo: Perceptron Simples
Tipo de aprendizado: Supervisionado
Problema: Classificação binária

O Perceptron é um modelo de neurônio artificial que realiza uma combinação linear das entradas seguida de uma função de ativação. Ele é utilizado para resolver problemas de classificação linearmente separáveis.


Neste exemplo, o modelo será aplicado na base Telco Customer Churn, cujo objetivo é identificar clientes com probabilidade de cancelar o serviço.


In [2]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import Perceptron
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

# carregar dataset
df = pd.read_csv("WA_Fn-UseC_-Telco-Customer-Churn.csv")

# transformar churn em número
df['Churn'] = df['Churn'].map({'Yes':1,'No':0})

# remover id
df = df.drop('customerID', axis=1)

# transformar categóricas
df = pd.get_dummies(df, drop_first=True)

# separar X e y
X = df.drop('Churn', axis=1)
y = df['Churn']

# divisão treino teste
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.3,random_state=42)

# normalização
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

# modelo
model = Perceptron(max_iter=1000)

model.fit(X_train,y_train)

# previsão
y_pred = model.predict(X_test)

print("Accuracy:", accuracy_score(y_test,y_pred))
print(classification_report(y_test,y_pred))
print(confusion_matrix(y_test,y_pred))

Accuracy: 0.7368670137245622
              precision    recall  f1-score   support

           0       0.74      0.98      0.84      1539
           1       0.62      0.08      0.14       574

    accuracy                           0.74      2113
   macro avg       0.68      0.53      0.49      2113
weighted avg       0.71      0.74      0.65      2113

[[1510   29]
 [ 527   47]]


Interpretação

O Perceptron apresentou desempenho moderado na tarefa de previsão de churn. Apesar de alcançar uma acurácia razoável, observa-se um recall baixo para a classe de clientes que cancelam o serviço.

Isso ocorre porque o Perceptron é um modelo linear e possui limitações para capturar relações complexas entre variáveis. Conforme discutido na aula, ele só consegue resolver problemas linearmente separáveis, o que limita sua capacidade em cenários mais complexos.

2️⃣ Rede Neural de Camada Única

Texto explicativo

Modelo: Rede Neural de Camada Única
Tipo de aprendizado: Supervisionado
Problema: Classificação multiclasse

As redes neurais de camada única possuem uma camada de entrada conectada diretamente à camada de saída. Elas representam uma evolução do perceptron simples e podem utilizar funções de ativação mais complexas, como Softmax para classificação multiclasse.

Neste exemplo utilizaremos o dataset Iris para classificar espécies de flores.

In [3]:
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report, confusion_matrix

# carregar dados
iris = load_iris()

X = iris.data
y = iris.target

# dividir
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.3,random_state=42)

# normalizar
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

# modelo camada única
model = LogisticRegression(max_iter=200)

model.fit(X_train,y_train)

y_pred = model.predict(X_test)

print(classification_report(y_test,y_pred))
print(confusion_matrix(y_test,y_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        19
           1       1.00      1.00      1.00        13
           2       1.00      1.00      1.00        13

    accuracy                           1.00        45
   macro avg       1.00      1.00      1.00        45
weighted avg       1.00      1.00      1.00        45

[[19  0  0]
 [ 0 13  0]
 [ 0  0 13]]


Interpretação

A rede neural de camada única apresenta melhor capacidade de generalização quando comparada ao perceptron simples. Isso ocorre porque a função de ativação utilizada permite representar relações mais complexas entre as variáveis.

Entretanto, por possuir apenas uma camada, esse modelo ainda apresenta limitações estruturais e pode sofrer underfitting em problemas mais complexos.

3️⃣ Rede Neural Multicamadas (MLP)

Texto explicativo

Modelo: Multilayer Perceptron (MLP)
Tipo de aprendizado: Supervisionado
Problema: Classificação

As redes neurais multicamadas possuem uma ou mais camadas ocultas entre a entrada e a saída. Essas camadas permitem que o modelo capture relações não lineares complexas entre as variáveis, aumentando significativamente a capacidade de aprendizado do modelo.

In [4]:
from sklearn.datasets import load_digits
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.neural_network import MLPClassifier
from sklearn.metrics import classification_report, confusion_matrix

digits = load_digits()

X = digits.data
y = digits.target

X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.3,random_state=42)

scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

model = MLPClassifier(hidden_layer_sizes=(128,),
                      activation='relu',
                      max_iter=300)

model.fit(X_train,y_train)

y_pred = model.predict(X_test)

print(classification_report(y_test,y_pred))
print(confusion_matrix(y_test,y_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        53
           1       1.00      1.00      1.00        50
           2       0.96      1.00      0.98        47
           3       1.00      0.94      0.97        54
           4       0.98      1.00      0.99        60
           5       0.98      0.97      0.98        66
           6       0.98      0.98      0.98        53
           7       1.00      0.98      0.99        55
           8       0.98      1.00      0.99        43
           9       0.97      0.98      0.97        59

    accuracy                           0.99       540
   macro avg       0.99      0.99      0.99       540
weighted avg       0.99      0.99      0.99       540

[[53  0  0  0  0  0  0  0  0  0]
 [ 0 50  0  0  0  0  0  0  0  0]
 [ 0  0 47  0  0  0  0  0  0  0]
 [ 0  0  2 51  0  1  0  0  0  0]
 [ 0  0  0  0 60  0  0  0  0  0]
 [ 0  0  0  0  0 64  1  0  0  1]
 [ 0  0  0  0  1  0 52  0  0  0]
 [ 0  0  0

Interpretação

O modelo MLP apresentou desempenho superior aos modelos anteriores. Isso ocorre porque as camadas ocultas permitem que o modelo aprenda padrões não lineares complexos presentes nos dados.

Dessa forma, redes neurais multicamadas possuem maior capacidade de generalização e são amplamente utilizadas em aplicações como reconhecimento de imagem, processamento de linguagem natural e previsão de séries temporais.

Evolução dos Modelos de Redes Neurais

Diferença entre Perceptron e MLP

O Perceptron possui apenas uma camada e é capaz de resolver apenas problemas linearmente separáveis. Já o MLP possui múltiplas camadas ocultas, permitindo capturar relações não lineares entre os dados.

Por que múltiplas camadas aumentam a capacidade do modelo

As camadas ocultas realizam transformações sucessivas nos dados, permitindo que a rede aprenda representações mais complexas e hierárquicas.

O que significa não linearidade

Não linearidade significa que o modelo consegue representar relações que não podem ser separadas por uma linha ou plano simples.

Relação com overfitting

Redes neurais muito complexas podem memorizar os dados de treino, gerando baixo erro no treinamento mas pior desempenho em novos dados.

Quando redes neurais são mais vantajosas

Redes neurais são especialmente úteis em problemas complexos como:

reconhecimento de imagens

processamento de linguagem natural

detecção de padrões complexos

grandes volumes de dados